### ISSUE TITLE
Example Configuration

### ISSUE THREAD

**Issue by wwselleck** [wwselleck/tusk#1]
This is an evolving draft of what a tusk configuration file would look like.

```toml
[task]
    [tasks.link]
    plugin = "link"

    [[tasks.link.links]]
    source = ".vimrc"
    dest = "~/.vimrc"
    
    [tasks.brew]
    plugin = "brew"
    programs = [ "neovim/neovim/neovim", "rust"]

[plans]
bootstrap = [ "brew", "link" ]
```
